In [1]:
# Importing the required libraries
import numpy as np
import pandas as pd
import math
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [2]:
# Readin the Training dataset
data = pd.read_csv('Turbulence_Train.csv')

In [3]:
# Replacing all themissing values
data = data.replace('M',0)

In [4]:
pd.isnull(data).sum()

Wind Speed Knots    0
gust                0
skyl1               0
skyl2               0
skyl3               0
skyl4               0
peak_wind_gust      0
Turbulence          0
dtype: int64

In [5]:
data

Wind Speed Knots gust skyl1  skyl2  skyl3 skyl4 peak_wind_gust  \
0                  13    0  6000      0      0     0              0   
1                  11    0  6000      0      0     0              0   
2                  13    0     0      0      0     0              0   
3                  16    0     0      0      0     0              0   
4                  13    0     0      0      0     0              0   
..                ...  ...   ...    ...    ...   ...            ...   
293                15    0  8000  27000      0     0              0   
294                17    0  8500  27000      0     0              0   
295                13    0  8500  20000  27000     0              0   
296                13    0  8500  20000  27000     0              0   
297                14    0  8500  27000      0     0              0   

     Turbulence  
0             0  
1             0  
2             0  
3             0  
4             0  
..          ...  
293           0  
294           0  
295           0  
296           0  
297           0  

[298 rows x 8 columns]

In [6]:
# Splitting into X and Y
X = data.iloc[:,:-1]
Y = data.iloc[:,-1]

In [7]:
X

Wind Speed Knots gust skyl1  skyl2  skyl3 skyl4 peak_wind_gust
0                  13    0  6000      0      0     0              0
1                  11    0  6000      0      0     0              0
2                  13    0     0      0      0     0              0
3                  16    0     0      0      0     0              0
4                  13    0     0      0      0     0              0
..                ...  ...   ...    ...    ...   ...            ...
293                15    0  8000  27000      0     0              0
294                17    0  8500  27000      0     0              0
295                13    0  8500  20000  27000     0              0
296                13    0  8500  20000  27000     0              0
297                14    0  8500  27000      0     0              0

[298 rows x 7 columns]

In [8]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
293    0
294    0
295    0
296    0
297    0
Name: Turbulence, Length: 298, dtype: int64

In [9]:
# Using Test Train split
X_train, X_dev, Y_train, Y_dev = train_test_split(X, Y, test_size = 0.25, random_state = 777)

In [10]:
print(X_train.shape)
print(X_dev.shape)

print(Y_train.shape)
print(Y_dev.shape)

(223, 7)
(75, 7)
(223,)
(75,)


In [11]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_dev = sc.transform(X_dev)

In [12]:
# Logistic regression model
linreg = LogisticRegression()

In [13]:
linreg.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
# Predicting to check for Validation
linregpred = linreg.predict(X_dev)

In [15]:
from sklearn import metrics
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [16]:
#print('Mean Absolute Error:', metrics.mean_absolute_error(Y_dev, linregpred))
#print('Mean Squared Error:', metrics.mean_squared_error(Y_dev, linregpred))
#print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_dev, linregpred)))

In [17]:
#print(classification_report(Y_dev, linregpred))

TESTING

In [18]:
# Reading the testing data
X_testinc = pd.read_csv('Turb_Test.csv')

In [19]:
# Replacing missing values
X_testinc = X_testinc.replace('M',0)

In [20]:
# Viewing data before shuffle
X_testinc

STATION     TIME  Wind Speed Knots gust skyl1 skyl2 skyl3  skyl4  \
0     JFK  5:51:00                10    0     0     0     0      0   
1     PIT  5:51:00                 4    0  4400     0     0      0   
2     CMH  6:51:00                 3    0  1200     0     0      0   
3     IND  6:54:00                 3    0  6500  8000     0      0   
4     AAO  6:54:00                10    0   500     0     0      0   
5     COS  7:54:00                14   21  2500  5000  8500      0   
6     LAS  7:56:00                 6    0     0     0     0      0   
7     LAX  8:53:00                 0    0     0     0     0      0   

   peak_wind_gust  
0               0  
1               0  
2               0  
3               0  
4               0  
5               0  
6               0  
7               0

In [21]:
temp = X_testinc.to_numpy()
np.random.shuffle(temp)
tempo = pd.DataFrame(temp)


In [22]:
# Viewing data after shuffle
tempo

0        1   2   3     4     5     6  7  8
0  IND  6:54:00   3   0  6500  8000     0  0  0
1  COS  7:54:00  14  21  2500  5000  8500  0  0
2  PIT  5:51:00   4   0  4400     0     0  0  0
3  AAO  6:54:00  10   0   500     0     0  0  0
4  LAS  7:56:00   6   0     0     0     0  0  0
5  JFK  5:51:00  10   0     0     0     0  0  0
6  CMH  6:51:00   3   0  1200     0     0  0  0
7  LAX  8:53:00   0   0     0     0     0  0  0

In [23]:
# Saves the region code and the time for later access
Label = tempo.iloc[:,0]
Time = tempo.iloc[:,1]


In [24]:
X_test = tempo.iloc[:,2:]
X_test = X_test.to_numpy()

In [25]:
X_test

array([[3, 0, '6500', '8000', 0, 0, 0],
       [14, '21', '2500', '5000', '8500', 0, 0],
       [4, 0, '4400', 0, 0, 0, 0],
       [10, 0, '500', 0, 0, 0, 0],
       [6, 0, 0, 0, 0, 0, 0],
       [10, 0, 0, 0, 0, 0, 0],
       [3, 0, '1200', 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [26]:
# Transforming the test data on the model 
X_test = sc.transform(X_test)

In [27]:
X_test

array([[-1.68401285, -0.68631103, -0.04627535,  0.11403295, -0.41773526,
        -0.17644203, -0.57281985],
       [ 0.19537001,  1.01331592, -0.5661445 , -0.19798359,  0.76214431,
        -0.17644203, -0.57281985],
       [-1.51315987, -0.68631103, -0.31920665, -0.71801117, -0.41773526,
        -0.17644203, -0.57281985],
       [-0.48804194, -0.68631103, -0.82607908, -0.71801117, -0.41773526,
        -0.17644203, -0.57281985],
       [-1.17145389, -0.68631103, -0.89106272, -0.71801117, -0.41773526,
        -0.17644203, -0.57281985],
       [-0.48804194, -0.68631103, -0.89106272, -0.71801117, -0.41773526,
        -0.17644203, -0.57281985],
       [-1.68401285, -0.68631103, -0.73510198, -0.71801117, -0.41773526,
        -0.17644203, -0.57281985],
       [-2.19657182, -0.68631103, -0.89106272, -0.71801117, -0.41773526,
        -0.17644203, -0.57281985]])

In [28]:
# Predicting values for the test data
linregprednew = linreg.predict(X_test)

In [29]:
# Result of Turbulence 1-Yes and 0-No
linregprednew

array([0, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [32]:
# Computation to check region of Turbulence
Finval = []
for i in range(linregprednew.shape[0]):
    Radar = []
    TimeRange = []
    if(linregprednew[i] == 1):
        Radar.append(Label[i])
        TimeRange.append(Time[i])
        Finval.append([Radar,TimeRange])   

In [33]:
# Region and time of Turbulence occurence (Turbulence target val = 1)
Finval

[[['COS'], ['7:54:00']]]

In [34]:
# Computation to check region of NO Turbulence
Finval = []
for i in range(linregprednew.shape[0]):
    Radar = []
    TimeRange = []
    if(linregprednew[i] == 0):
        Radar.append(Label[i])
        TimeRange.append(Time[i])
        Finval.append([Radar,TimeRange]) 

In [35]:
# Region and time of Turbulence occurence (Turbulence target val = 0)
Finval

[[['IND'], ['6:54:00']],
 [['PIT'], ['5:51:00']],
 [['AAO'], ['6:54:00']],
 [['LAS'], ['7:56:00']],
 [['JFK'], ['5:51:00']],
 [['CMH'], ['6:51:00']],
 [['LAX'], ['8:53:00']]]

HELPFUL INFO:

JFK – John F Kennedy Airport NY
PIT - Pittsburgh International Airport PA
CMH - John Glenn Columbus International Airport OH
IND - Indianapolis International Airport IN
AAO - Colonel James Jabara Airport KA
COS - Colorado Springs Airport CO
LAS - McCarran International Airport NV
LAX - Los Angeles International Airport CA